version: "3"
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - nextjs
  nextjs:
    build: ./docker/
    container_name: jira-nextjs
    volumes:
      - ./app:/usr/src/app
    command: "yarn dev"
    ports:
      - "3000:3000"
